//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "class")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::attr::Entity")]
	Attr,
	#[sea_orm(has_many = "super::item::Entity")]
	Item,
}

impl Related<super::attr::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Attr.def()
	}
}

impl Related<super::item::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Item.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
