[paths]
# All paths are relative to the location of this file.
#
# The last component of each path will be created automatically.
# if any parents are missing, ufo will not start.

# In-progress uploads are stored here. This shouldn't be a ramdisk,
# files have an arbitrary size.
# THIS DIRECTORY IS CLEARED EVERY TIME THE SERVER STARTS.
upload_dir = "./tmp"

# Where to store datasets. Will get pretty big.
dataset_dir = "./datasets"

# Path to main database file.
main_db = "./ufo.sqlite"


[network]
# Address and port to bind to
server_addr = "127.0.0.1:3030"

# Max request body size, in bytes
# If you're using a reverse proxy, make sure it
# is also configured for requests of this size.
request_body_limit = 2_000_000


[pipeline]
# The maximum size, in bytes, of a binary fragment in the pipeline.
# Smaller values slow down pipelines; larger values use more memory.
# The default of 2mb is usually fine.
blob_fragment_size = 2_000_000

# Pipeline parallelism configuration.
# We'll run `parallel_jobs` jobs at once, allowing each to use at most
# `threads_per_job` threads.
#
# Note that a pipeline runner can't always utilize all the threads it is
# allowed to use. Therefore, the runner will rarely---if ever---use all
# `parallel_jobs * threads_per_job` threads it is allowed to start.
#
# It is probably a good idea to set `parallel_jobs` to *roughly* your cpu's core count.
# A large `threads_per_job` will rarely affect the performance of most workloads.
parallel_jobs = 4
threads_per_job = 4


[logging]
# Log level config.
# These defaults make sense unless you're tracking down a bug.
#
# - sqlx: Log level for sqlx (sql queries)
# - http: Log level for axum (web server)
# - pipeline: Log level for pipeline runner
# - server: Log level for copperd core (auth, api, etc)
# - all: Log level for all other sources. This can get noisy.
level.sqlx = "Info"
level.http = "Info"
level.pipeline = "Info"
level.server = "Info"
level.all = "Warn"
