# The maximum size, in bytes, of a blob channel fragment
# larger fragments make the runner use more memory, but make it run faster.
# fragments should not be absurdly large, diminishing returns.
blob_fragment_size = 2097152

[network]
# Address and port to bind to
server_addr = "127.0.0.1:3030"

# Max request body size, in bytes
request_body_limit = 2097152 # 2 megabytes

[paths]
# All paths are relative to the location of this file.
#
# The last component of each path will be created automatically.
# if any parents are missing, ufo will not start.

# In-progress uploads are stored here. This shouldn't be a ramdisk,
# files have an arbitrary size.
# THIS DIRECTORY IS CLEARED EVERY TIME THE SERVER STARTS.
upload_dir = "./tmp"

# Where to store datasets. Will get pretty big.
dataset_dir = "./datasets"

# Path to main database file.
main_db = "./ufo.sqlite"
