services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 256mb

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin

    volumes:
      - ./data/minio:/data

    command: server /data --console-address ":9001"
