[pipeline]
# outputs for the "pipeline" node
# (These are pipeline *inputs*, but node *outputs*)
input."data" = "binary"

# inputs for the pipeline node
output."album" = "text"
output."artist" = "text"
output."empty" = "text"

# Connect pipeline node inputs
outmap."album" = "if_none.out"
outmap."artist" = "tags.artist"

[node."tags"]
type = "ExtractTag"
input.data = "pipeline.data"

#[node."getcover"]
#type = "CoverExtract"
#input.data = "fs.data"

[node.if_none]
type = "IfNone"
input.data = "tags.album"
#input.data = "if_none.out"
input.ifnone = { "text" = "Unknown" }
