[config]
input.type = "File"

output.type = "DataSet"
output.class = "AudioFile"

output_map."album" = "if_none.out"
output_map."artist" = "tags.artist"


[node."tags"]
type = "ExtractTag"
input.data = "pipeline.data"

#[node."getcover"]
#type = "CoverExtract"
#input.data = "fs.data"

[node.if_none]
type = "IfNone"
input.data = "tags.album"
#input.data = "if_none.out"
input.ifnone = { "text" = "Unknown" }
