# eslint and typescript versions are restricted
# by nextjs.

depcheck:
  ignoreMatches:
    [
      "postcss-preset-mantine",
      "@svgr/webpack",
      "@types/node",
      "@types/react-dom",
    ]
