[[bin]]
name = "edged"
path = "src/main.rs"

[package]
name = "edged"
description = "Copper edge daemon"
categories = { workspace = true }
keywords = { workspace = true }
version = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }

[lints]
workspace = true

[dependencies]
copper-util = { workspace = true }
copper-migrate = { workspace = true }
copper-edged = { workspace = true }
copper-storage = { workspace = true }
copper-pipelined = { workspace = true }
copper-jobqueue = { workspace = true }

aws-sdk-s3 = { workspace = true }
aws-config = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
tower-http = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
smartstring = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
sqlx = { workspace = true }
async-trait = { workspace = true }
rand = { workspace = true }
time = { workspace = true }
