import {
	IconAdjustmentsAlt,
	IconAmpersand,
	IconAnalyze,
	IconArrowRight,
	IconBinary,
	IconBinaryTree,
	IconCheck,
	IconChevronDown,
	IconChevronLeftPipe,
	IconChevronRightPipe,
	IconCircleOff,
	IconCpu,
	IconDatabase,
	IconDatabaseCog,
	IconDatabasePlus,
	IconDatabaseX,
	IconDecimal,
	IconDots,
	IconEdit,
	IconFile,
	IconFileDigit,
	IconFilePlus,
	IconFileUpload,
	IconFileX,
	IconFolder,
	IconFolderPlus,
	IconFolderX,
	IconFolders,
	IconGridPattern,
	IconHexagon,
	IconHexagon3,
	IconHexagonMinus,
	IconHexagonPlus,
	IconLetterCase,
	IconList,
	IconListDetails,
	IconLock,
	IconMenu2,
	IconPlus,
	IconSchema,
	IconSend,
	IconServer2,
	IconSettings2,
	IconSortAscending2,
	IconSortDescending2,
	IconSquareAsterisk,
	IconTableRow,
	IconTrash,
	IconUpload,
	IconUser,
	IconUserOff,
	IconUserPlus,
	IconUsers,
	IconUsersGroup,
	IconX,
} from "@tabler/icons-react";
import { CSSProperties } from "react";

const defaultStyles: CSSProperties | undefined = {
	strokeWidth: "1.5px",
	width: "100%",
	height: "1.5rem",
	margin: "auto",
};

// This module lets us apply default styling to tabler icons,
// and makes it easy to replace our icon provider.

export const XIcon = (params: { icon: any; style?: CSSProperties }) => {
	return <params.icon style={{ ...defaultStyles, ...params.style }} />;
};
