[input]
type = "File"

[output]
node.type = "AddToDataset"
node.class = "AudioFile"

input."album" = { node = "tags", output = "Album" }
input."artist" = { node = "tags", output = "Artist" }
input."albumartist" = { node = "tags", output = "AlbumArtist" }
input."tracknumber" = { node = "tags", output = "TrackNumber" }
input."year" = { node = "tags", output = "Year" }
input."genre" = { node = "tags", output = "Genre" }
input."ISRC" = { node = "tags", output = "ISRC" }
input."lyrics" = { node = "if_none", output = "out" }
input."audio_data" = { node = "strip", output = "out" }
input."cover_art" = { node = "add_cover", output = "added_item" }


[node."tags"]
node.type = "ExtractTags"
node.tags = [
	"Album",
	"Artist",
	"AlbumArtist",
	"TrackNumber",
	"Year",
	"Genre",
	"ISRC",
	"Lyrics",
]
input.data = { "pipeline" = "data" }

[node.if_none]
node.type = "IfNone"
node.data_type = "text"
input."data" = { node = "tags", output = "Lyrics" }
input."ifnone" = { type = "Constant", value = "Unknown Lyrics" }

[node.strip]
node.type = "StripTags"
input."data" = { pipeline = "data" }
#after = ["add_cover"]

[node."extract_cover"]
node.type = "ExtractCovers"
input."data" = { pipeline = "data" }

[node."add_cover"]
node.type = "Pipeline"
node.pipeline = "cover"
input."cover_data" = { node = "extract_cover", output = "cover_data" }

[node."print"]
node.type = "Print"
input."data" = { node = "add_cover", output = "added_item" }
