[input]
type = "File"

[output]
node.type = "AddItem"
node.class = "AudioFile"
input."title" = { node = "tags", output = "Title" }
input."album" = { node = "tags", output = "Album" }
input."artist" = { node = "tags", output = "Artist" }
input."albumartist" = { node = "tags", output = "AlbumArtist" }
input."tracknumber" = { node = "tags", output = "TrackNumber" }
input."year" = { node = "tags", output = "Year" }
input."genre" = { node = "tags", output = "Genre" }
input."ISRC" = { node = "tags", output = "ISRC" }
input."lyrics" = { node = "tags", output = "Lyrics" }
input."audio_data" = { node = "strip", output = "out" }
input."audio_hash" = { node = "hash_audio", output = "hash" }
input."cover_art" = { node = "find", output = "found_item" }


[node."tags"]
node.type = "ExtractTags"
node.tags = [
	"Title",
	"Album",
	"Artist",
	"AlbumArtist",
	"TrackNumber",
	"Year",
	"Genre",
	"ISRC",
	"Lyrics",
]
input.data = { "pipeline" = "data" }

[node.strip]
node.type = "StripTags"
input."data" = { pipeline = "data" }

[node."hash_audio"]
node.type = "Hash"
node.hash_type = "SHA256"
input."data" = { node = "strip", output = "out" }


[node."extract_cover"]
node.type = "ExtractCovers"
input."data" = { pipeline = "data" }

[node."hash_cover"]
node.type = "Hash"
node.hash_type = "SHA256"
input."data" = { node = "extract_cover", output = "cover_data" }

[node."add_cover"]
node.type = "AddItem"
node.class = "CoverArt"
node.allow_non_unique = true
input."content_hash" = { node = "hash_cover", output = "hash" }
input."image_data" = { node = "extract_cover", output = "cover_data" }

[node."find"]
node.type = "FindItem"
node.class = "CoverArt"
node.by_attr = "content_hash"
input."attr_value" = { node = "hash_cover", output = "hash" }
after = ["add_cover"]
