[input]
type = "Noop"
input."cover_data" = "binary"

[output]
node.type = "AddToDataset"
node.class = "CoverArt"

input."content_hash" = { node = "hash", output = "hash" }
input."image_data" = { pipeline = "cover_data" }


[node."hash"]
node.type = "Hash"
node.hash_type = "SHA256"
input."data" = { pipeline = "cover_data" }
