[config.input]
type = "Noop"
input."cover_data" = "binary"

[config.output]
type = "Dataset"
class = "CoverArt"
attr."image_data" = "binary"
attr."content_hash" = "text"

[config.output_map]
"content_hash" = { node = "hash", output = "hash" }
"image_data" = { pipeline = "cover_data" }


[node."hash"]
node.type = "Hash"
input."data" = { pipeline = "cover_data" }
