[[bin]]
name = "pipelined"
path = "src/main.rs"

[package]
name = "pipelined"
description = "Copper pipeline runner"
categories = { workspace = true }
keywords = { workspace = true }
version = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }

[lints]
workspace = true

[dependencies]
copper-util = { workspace = true }
copper-pipelined = { workspace = true }
copper-storaged = { workspace = true }
# Node implementations
pipelined-audiofile = { workspace = true }
pipelined-storaged = { workspace = true }
pipelined-basic = { workspace = true }

reqwest = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
tower-http = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
smartstring = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
axum = { workspace = true }
crossbeam = { workspace = true }
