on: push
name: Cargo test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ./copperd
      run: cargo build
    - name: Test
      working-directory: ./copperd
      run: cargo test --workspace
