on: push
name: Cargo fmt

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  cargo_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo fmt
        working-directory: ./copperd
        run: cargo fmt --check
