on: push
name: Cargo clippy

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clippy
        working-directory: ./copperd
        run: cargo clippy --all-targets --all-features
