on: push
name: Lints

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clippy
        working-directory: ./copperd
        run: cargo clippy --all-targets --all-features

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check typos
        uses: crate-ci/typos@master
        with:
          config: ./typos.toml

  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: lychee-cache
          restore-keys: lychee-cache
          #key: cache-lychee-${{ github.sha }}
          #restore-keys: cache-lychee-
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --config lychee.toml .
